services:
  server:
    image: iron2ron/moapick:latest
    build: ./
    ports:
      - "80:8080"
    develop:
      watch:
        - path: ./
          action: rebuild
          ignore:
            - tartget/
    depends_on:
      - pg
  pg:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: moapick
volumes:
  dbdata:
