services:
  webserver:
    image: caddy
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from moapick.p-e.kr --to server:8080
  server:
    image: iron2ron/moapick:latest
    depends_on:
      - pg
  pg:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: moapick
volumes:
  dbdata:
