version: "3.7"
services:
  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
  server:
    image: moapick:latest
    depends_on:
      - pg
    restart: unless-stopped
  pg:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: moapick
    restart: unless-stopped
volumes:
  dbdata:
  caddy_data:
  caddy_config:
