services:
  webserver:
    image: caddy
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --to server:8080
  server:
    image: iron2ron/moapick:latest
    build: ./
    develop:
      watch:
        - path: ./
          action: rebuild
          ignore:
            - tartget/
    depends_on:
      - pg
  pg:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: moapick
volumes:
  dbdata:
